name: web_framework_flutter_api_example
description: "Demonstrates how to use the web_framework_flutter_api plugin."

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  url_launcher: ^6.3.0


  web_framework_flutter_api:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/configs/
    - assets/executors/
