name: web_framework_flutter_api
description: "C++ HTTP/HTTPS web server with Flutter API for Android and Windows"
version: 1.0.7
homepage: https://github.com/Lazypanda07/WebFramework

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.3
  crypto: ^3.0.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lazypanda07.web_framework_flutter_api
        pluginClass: WebFrameworkFlutterApiPlugin
      windows:
        pluginClass: WebFrameworkFlutterApiPluginCApi
