name: "Build WebFramework"


on:
  workflow_call:
    inputs:
      os:
        description: "runs-on OS"
        required: true
        type: string
      image:
        description: "Custom Docker image"
        required: false
        type: string
      configuration:
        description: "Build configuration"
        required: true
        type: string
      build-parameters:
        description: "CMake build parameters"
        required: true
        type: string
      cmake-generator:
        description: "CMake generator"
        required: false
        type: string
        default: "Ninja"
      upload-artifact-name:
        description: "Name of uploaded artifact zip"
        required: false
        type: string
      python-version:
        description: "Python version for Windows build"
        required: false
        type: string
        default: ''


jobs:
  build:
    runs-on: ${{ inputs.os }}
    container: 
      image: ${{ inputs.image }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Enable NMake
      if: ${{ inputs.os == 'windows-latest' }}
      uses: ilammy/msvc-dev-cmd@v1.13.0
      
    - name: Install Python
      if: ${{ inputs.python-version != '' }}
      uses: actions/setup-python@v6
      with:
        python-version: "${{ inputs.python-version }}"

    - name: Build
      shell: bash
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=../WebFrameworkLibrary -DCMAKE_BUILD_TYPE=${{ inputs.configuration }} ${{ inputs.build-parameters }} -G ${{ inputs.cmake-generator }} ..
          cmake --build . --config ${{ inputs.configuration }} -j
          cmake --install . --config ${{ inputs.configuration }}
  
    - name: Upload artifacts
      if: ${{ inputs.upload-artifact-name != '' }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.upload-artifact-name }}
        path: WebFrameworkLibrary
