name: Build SQLite


on:
  push:
    branches: [dev]
  workflow_dispatch:
  

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - name: Download latest SQLite
      uses: robinraju/release-downloader@v1.9
      with:
        repository: sqlite/sqlite
        latest: true
        extract: true
        zipBall: true
        tarBall: false
        
    - name: LS
      shell: bash
      run: ls

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Get SQLite
      run: |
          wget https://github.com/sqlite/sqlite/archive/refs/tags/version-3.45.2.zip
          unzip version-3.45.2.zip -d .

    - name: LS
      shell: bash
      run: ls
          
    - name: Build
      working-directory: version-3.45.2
      run: |
          mkdir build
          cd build
          ../sqlite/configure
          make
          make sqlite3.c
