name: CI

on:
  push:
    branches: [master, dev]


jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]
  
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DSHARED_WEB_FRAMEWORK=${{ matrix.shared[0] }} -G "NMake Makefiles" ..
          nmake install

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Windows
        path: build/install-dir


  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
          export CC=/usr/bin/gcc-13
          export CXX=/usr/bin/g++-13
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DSHARED_WEB_FRAMEWORK=${{ matrix.shared[0] }} ..
          make install -j $(nproc)
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Linux
        path: build/install-dir
        

  windows-tests:
    runs-on: windows-latest
    needs: windows-build
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]
        config: [config.json, threadPoolConfig.json]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Windows
        path: WebFrameworkLibrary

    - name: Get Google Test
      uses: LazyPanda07/get-gtest@v1
      with:
        build-type: ${{ matrix.configuration }}
        install-path: Tests/gtest

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build tests
      working-directory: Tests
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -G "NMake Makefiles" ..
          nmake install

    - name: Tests
      working-directory: Tests
      run: |
          cd build/bin
          .\Tests.exe ${{ matrix.config }}


  linux-tests:
    runs-on: ubuntu-latest
    needs: linux-build
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]
        config: [config.json, threadPoolConfig.json]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Linux
        path: WebFrameworkLibrary

    - name: Get Google Test
      uses: LazyPanda07/get-gtest@v1
      with:
        install-path: Tests/gtest

    - name: Build tests
      working-directory: Tests
      run: |
          export CC=/usr/bin/gcc-13
          export CXX=/usr/bin/g++-13
          mkdir build
          cd build
          cmake ..
          make install -j $(nproc)

    - name: Tests
      working-directory: Tests
      run: |
          cd build/bin
          LD_LIBRARY_PATH=$(pwd):${LD_LIBRARY_PATH} ./Tests ${{ matrix.config }}
  

  memory-leak-tests:
    runs-on: ubuntu-latest
    needs: linux-build
    strategy:
      matrix:
        configuration: [Debug, Release]
        shared: [[ON, DLL], [OFF, ""]]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.configuration }}${{ matrix.shared[1] }}_Linux
        path: WebFrameworkLibrary

    - name: Get Google Test
      uses: LazyPanda07/get-gtest@v1
      with:
        install-path: Tests/gtest
        
    - name: Build tests
      working-directory: Tests
      run: |
          export CC=/usr/bin/gcc-13
          export CXX=/usr/bin/g++-13
          mkdir build
          cd build
          cmake ..
          make install -j $(nproc)

    - name: Memory leak test
      uses: LazyPanda07/check-memory-leaks@v1.2
      with:
        path: Tests/build/bin
        name: Tests
        leak-kinds: definite,indirect,reachable
        pre-execute: export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)
        args: ${{ matrix.config }}
        