name: Distribution


on:
  push:
    tags:
      - "v*.*.*"


jobs:
  flutter-package:
    runs-on: ubuntu-latest
    container:
      image: lazypanda07/ubuntu_cxx20:android

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get Windows latest release
      uses: robinraju/release-downloader@v1.11
      with:
        repository: ${{ github.repository }}
        latest: true
        extract: true
        fileName: windows.zip

    - name: Get Android latest release
      uses: robinraju/release-downloader@v1.11
      with:
        repository: ${{ github.repository }}
        latest: true
        extract: true
        fileName: android.zip

    - name: Copy libraries
      run: |
          mkdir -p API/web_framework_flutter_api/assets/lib/arm64-v8a
          cp -r ReleaseDLL_Windows/dll/*.dll API/web_framework_flutter_api/assets/lib
          cp -r Release_Android/lib/arm64-v8a/*.so API/web_framework_flutter_api/assets/lib/arm64-v8a

    - name: Dry run
      working-directory: API/web_framework_flutter_api
      run: dart pub publish --dry-run

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-package
        path: API/web_framework_flutter_api


  publish-flutter-package:
    runs-on: ubuntu-latest
    needs: flutter-package
    permissions:
      id-token: write
    env:
      flutter-version: 3.27.1

    steps:
    - uses: dart-lang/setup-dart@v1
  
    - name: Install Flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        channel: stable
        flutter-version: ${{ env.flutter-version }}

    - name: Download Flutter package
      uses: actions/download-artifact@v4
      with:
        name: flutter-package
        path: package

    - name: Install dependencies
      working-directory: package
      run: dart pub get

    - name: Publish dart package
      working-directory: package
      run: dart pub publish --force
