name: "Memory Leaks"


on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main


jobs:
  memory-leak-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04
    strategy:
      matrix:
        config: [multi_threaded_config.json, thread_pool_config.json, multi_threaded_config_https.json, thread_pool_config_https.json]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        
    - name: Build
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=../WebFrameworkLibrary -DWITH_PYTHON_EXECUTORS=OFF -DWITH_DOTNET_EXECUTORS=OFF -DBUILD_CSHARP_API=OFF -DBUILD_PYTHON_API=OFF -G "Ninja" ..
          cmake --build . -j
          cmake --install .
      
    - name: Build tests
      working-directory: Tests
      run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_ADDRESS_SANITIZER=ON -G "Ninja" ..
          cmake --build . -j
          cmake --install .

    - name: Tests
      working-directory: Tests/build/bin
      shell: bash
      run: |
        redis-server --port 10010 --requirepass password & sleep 1
        source run_memory_leak_tests.sh ${{ matrix.config }}
