name: "Run test"


on:
  workflow_call:
    inputs:
      os:
        description: "runs-on OS"
        required: true
        type: string
      image:
        description: "Custom Docker image"
        required: false
        type: string
      executors-api:
        description: "Executors build API"
        required: true
        type: string
      web-framework-config:
        description: "WebFramework config"
        required: true
        type: string
      test-script:
        description: "Script for running tests"
        required: true
        type: string
      python-version:
        description: "Python version"
        required: false
        type: string
        default: ''
      dotnet:
        description: ".NET option"
        required: false
        type: boolean
        default: false


jobs:
  build:
    runs-on: ${{ inputs.os }}
    container: 
      image: ${{ inputs.image }}
    env:
      actual-python-version: ''

    steps:  
    - name: Prepare download artifact name from Windows
      if: ${{ inputs.os == 'windows-latest' }}
      shell: bash
      run: |
        echo "CURRENT_OS=Windows" >> ${GITHUB_ENV}
        echo "DOWNLOAD_ARTIFACT_NAME=Windows" >> ${GITHUB_ENV}

    - name: Prepare download artifact name from Linux
      if: ${{ inputs.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        echo "CURRENT_OS=Linux" >> ${GITHUB_ENV}
        echo "DOWNLOAD_ARTIFACT_NAME=Linux" >> ${GITHUB_ENV}
      
    - name: Prepare download artifact name from Python
      shell: bash
      run: |
        echo "DOWNLOAD_ARTIFACT_NAME=${DOWNLOAD_ARTIFACT_NAME}-WITH_PYTHON_EXECUTORS=ON-BUILD_PYTHON_API=ON-${{ inputs.python-version }}" >> ${GITHUB_ENV}
        echo "actual-python-version=${{ inputs.python-version }}" >> ${GITHUB_ENV}

    - name: Append download artifact name if Python test script using
      if: ${{ inputs.python-version == '' && contains(inputs.test-script, 'python') }}
      shell: bash
      run: |
        echo "DOWNLOAD_ARTIFACT_NAME=${DOWNLOAD_ARTIFACT_NAME}-WITH_PYTHON_EXECUTORS=ON-BUILD_PYTHON_EXECUTORS=ON-3.14" >> ${GITHUB_ENV}
        echo "actual-python-version=3.14" >> ${GITHUB_ENV}

    - name: Prepare download artifact name from .NET
      shell: bash
      run: echo "DOWNLOAD_ARTIFACT_NAME=${DOWNLOAD_ARTIFACT_NAME}-WITH_DOTNET_EXECUTORS=ON-BUILD_CSHARP_API=ON" >> ${GITHUB_ENV}
      
    - name: Append download artifact name if C# test script using
      if: ${{ inputs.dotnet == false && contains(inputs.test-script, 'csharp') }}
      run: echo "DOWNLOAD_ARTIFACT_NAME=${DOWNLOAD_ARTIFACT_NAME}-WITH_DOTNET_EXECUTORS=ON-BUILD_CSHARP_API=ON" >> ${GITHUB_ENV}
      
    - name: Prepare download artifact name from CC ON
      if: ${{ inputs.executors-api == 'CC' }}
      shell: bash
      run: echo "DOWNLOAD_ARTIFACT_NAME=${DOWNLOAD_ARTIFACT_NAME}-BUILD_CC_API=ON" >> ${GITHUB_ENV}
    
    - name: Prepare download artifact name from CC OFF
      if: ${{ inputs.executors-api != 'CC' }}
      shell: bash
      run: echo "DOWNLOAD_ARTIFACT_NAME=${DOWNLOAD_ARTIFACT_NAME}-BUILD_CC_API=OFF" >> ${GITHUB_ENV}

    - name: Download ${{ env.DOWNLOAD_ARTIFACT_NAME }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.DOWNLOAD_ARTIFACT_NAME }}
        path: WebFrameworkLibrary

    - name: Download ${{ env.CURRENT_OS }}Tests
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.CURRENT_OS }}Tests
        path: Tests

    - name: Download ${{ env.CURRENT_OS }}Executors-${{ inputs.executors-api }}
      uses: actions/download-artifact@v7
      with:
        name: ${{ env.CURRENT_OS }}Executors-${{ inputs.executors-api }}
        path: Executors

    - name: Install Python
      if: ${{ env.actual-python-version != '' }}
      uses: actions/setup-python@v6
      with:
        python-version: "${{ env.actual-python-version }}"
        
    - name: Enable NMake
      if: ${{ inputs.os == 'windows-latest' }}
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Install Python API
      if: ${{ env.actual-python-version != '' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install WebFrameworkLibrary/api/python_api/dist/*.whl

    - name: Merge artifacts
      shell: bash
      run: |
          cp -r Executors/* Tests

          if [ -d "WebFrameworkLibrary/lib" ];
          then
            cp -r WebFrameworkLibrary/lib/* Tests  
          fi
          
          if [ -d "WebFrameworkLibrary/dll" ];
          then
            cp -rf WebFrameworkLibrary/dll/* Tests
          fi
          
    - name: Run ${{ inputs.test-script }} ${{ inputs.web-framework-config }} tests on Windows
      if: ${{ inputs.os == 'windows-latest' }}
      working-directory: Tests
      run: .\${{ inputs.test-script }} ${{ inputs.web-framework-config }}
    
    - name: Run ${{ inputs.test-script }} ${{ inputs.web-framework-config }} tests on Linux
      if: ${{ inputs.os == 'linux-latest' }}
      working-directory: Tests
      shell: bash
      run: source ${{ inputs.test-script }} ${{ inputs.web-framework-config }}
